OpenCBDC Transaction Processor: cbdc::sentinel_2pc::controller Class Reference
cbdc::sentinel_2pc::controller Class Reference
Manages a sentinel server for the two-phase commit architecture.
#include <controller.hpp>
Public Member Functions
controller ()=delete
controller (const controller &)=delete
auto operator= (const controller &) -> controller &=delete
controller (controller &&)=delete
auto operator= (controller &&) -> controller &=delete
controller (uint32_t sentinel_id, const config::options &opts, std::shared_ptr< logging::log > logger)
Constructor.
~controller () override=default
auto init () -> bool
Initializes the controller.
auto execute_transaction (transaction::full_tx tx, result_callback_type result_callback) -> bool override
Statically validates a transaction, submits it the shard coordinator network, and returns the result via a callback function.
Public Member Functions inherited from cbdc::sentinel::async_interface
virtual ~async_interface ()=default
async_interface ()=default
async_interface (const async_interface &)=delete
auto operator= (const async_interface &) -> async_interface &=delete
async_interface (async_interface &&)=delete
auto operator= (async_interface &&) -> async_interface &=delete
virtual auto execute_transaction (transaction::full_tx tx, result_callback_type result_callback) -> bool=0
Validate transaction on the sentinel, forward it to the coordinator network, and return the execution result using a callback function.
Additional Inherited Members
Public Types inherited from cbdc::sentinel::async_interface
using result_callback_type = std::function< void(std::optional< cbdc::sentinel::response >)>
Callback function for transaction execution result.
Detailed Description
Manages a sentinel server for the two-phase commit architecture.
Definition at line 21 of file twophase/sentinel_2pc/controller.hpp.
Constructor & Destructor Documentation
controller() [1/4]
cbdc::sentinel_2pc::controller::controller () delete
controller() [2/4]
cbdc::sentinel_2pc::controller::controller (const controller &) delete
controller() [3/4]
cbdc::sentinel_2pc::controller::controller (controller &&) delete
controller() [4/4]
cbdc::sentinel_2pc::controller::controller (uint32_t sentinel_id, const config::options & opts, std::shared_ptr< logging::log > logger)
Constructor.
Parameters
sentinel_id the running ID of this shard.
opts pointer to configuration options.
logger pointer shared logger.
Definition at line 15 of file twophase/sentinel_2pc/controller.cpp.
~controller()
cbdc::sentinel_2pc::controller::~controller () override default
Member Function Documentation
execute_transaction()
auto cbdc::sentinel_2pc::controller::execute_transaction (transaction::full_tx tx, result_callback_type result_callback) -> bool override virtual
Statically validates a transaction, submits it the shard coordinator network, and returns the result via a callback function.
Parameters
tx transaction to submit.
result_callback function to call with the execution result.
Returns
false if the sentinel was unable to forward the transaction to a coordinator.
Implements cbdc::sentinel::async_interface.
Definition at line 49 of file twophase/sentinel_2pc/controller.cpp.
References cbdc::transaction::validation::check_tx(), cbdc::sentinel::static_invalid, cbdc::transaction::validation::to_string(), cbdc::to_string(), and cbdc::transaction::tx_id().
init()
auto cbdc::sentinel_2pc::controller::init () -> bool
Initializes the controller.
Connects to the shard coordinator network and launches a server thread for external clients.
Returns
true if initialization succeeded.
Definition at line 27 of file twophase/sentinel_2pc/controller.cpp.
operator=() [1/2]
auto cbdc::sentinel_2pc::controller::operator= (const controller &) -> controller &=delete delete
operator=() [2/2]
auto cbdc::sentinel_2pc::controller::operator= (controller &&) -> controller &=delete delete
The documentation for this class was generated from the following files:
twophase/sentinel_2pc/controller.hpp
twophase/sentinel_2pc/controller.cpp