OpenCBDC Transaction Processor: cbdc::raft::node Class Reference
cbdc::raft::node Class Reference
A node in a raft cluster.
#include <node.hpp>
Public Member Functions
node ()=delete
node (const node &)=delete
auto operator= (const node &) -> node &=delete
node (node &&)=delete
auto operator= (node &&) -> node &=delete
node (int node_id, const network::endpoint_t &raft_endpoint, const std::string &node_type, bool blocking, nuraft::ptr< nuraft::state_machine > sm, size_t asio_thread_pool_size, std::shared_ptr< logging::log > logger, nuraft::cb_func::func_type raft_cb, bool wait_for_followers)
Constructor.
~node ()
auto init (const nuraft::raft_params &raft_params) -> bool
Initializes the NuRaft instance with the given state machine and raft parameters.
auto build_cluster (const std::vector< network::endpoint_t > &raft_servers) -> bool
Connect to each of the given raft nodes and join them to the cluster.
auto is_leader () const -> bool
Indicates whether this node is the current raft leader.
auto replicate (nuraft::ptr< nuraft::buffer > new_log, const callback_type &result_fn) const -> bool
Replicates the given log entry in the cluster.
auto replicate_sync (const nuraft::ptr< nuraft::buffer > &new_log) const -> std::optional< nuraft::ptr< nuraft::buffer > >
Replicates the provided log entry and returns the results from the state machine if the replication was successful.
auto last_log_idx () const -> uint64_t
Returns the last replicated log index.
auto get_sm () const -> nuraft::state_machine *
Returns a pointer to the state machine replicated by this raft node.
void stop ()
Shut down the NuRaft instance.
Detailed Description
A node in a raft cluster.
Wrapper for replicated state machine functionality using raft from the external library NuRaft. Builds a cluster with other raft nodes. Uses NuRaft to durably replicate log entries between a quorum of raft nodes. Callers provide a state machine to execute the log entries and return the execution result.
Definition at line 32 of file node.hpp.
Constructor & Destructor Documentation
node() [1/4]
cbdc::raft::node::node () delete
node() [2/4]
cbdc::raft::node::node (const node &) delete
node() [3/4]
cbdc::raft::node::node (node &&) delete
node() [4/4]
cbdc::raft::node::node (int node_id, const network::endpoint_t & raft_endpoint, const std::string & node_type, bool blocking, nuraft::ptr< nuraft::state_machine > sm, size_t asio_thread_pool_size, std::shared_ptr< logging::log > logger, nuraft::cb_func::func_type raft_cb, bool wait_for_followers)
Constructor.
Parameters
node_id identifier of the node in the raft cluster. Must be 0 or greater.
raft_endpoint TCP endpoint upon which to listen for incoming raft connections.
node_type name of the raft cluster this node will be part of.
blocking true if replication calls should block until the state machine makes an execution result available.
sm pointer to the state machine replicated by the cluster.
asio_thread_pool_size number of threads for processing raft messages. Set to 0 to use the number of cores on the system.
logger log instance NuRaft should use.
raft_cb NuRaft callback to report raft events.
wait_for_followers true if the leader raft node should re-attempt to add all followers to the cluster until success.
Definition at line 9 of file node.cpp.
~node()
cbdc::raft::node::~node ()
Definition at line 186 of file node.cpp.
References stop().
Member Function Documentation
build_cluster()
auto cbdc::raft::node::build_cluster (const std::vector< network::endpoint_t > & raft_servers) -> bool
Connect to each of the given raft nodes and join them to the cluster.
If this node is not node 0, this method blocks until node 0 joins this node to the cluster.
Parameters
raft_servers node endpoints of the other raft nodes in the cluster.
Returns
true if adding the nodes to the raft cluster succeeded.
Definition at line 130 of file node.cpp.
get_sm()
auto cbdc::raft::node::get_sm () const -> nuraft::state_machine*
Returns a pointer to the state machine replicated by this raft node.
Returns
pointer to the state machine.
Definition at line 194 of file node.cpp.
init()
auto cbdc::raft::node::init (const nuraft::raft_params & raft_params) -> bool
Initializes the NuRaft instance with the given state machine and raft parameters.
Parameters
raft_params NuRaft-specific parameters for the raft node.
Returns
true if the raft node initialized successfully.
Definition at line 38 of file node.cpp.
is_leader()
auto cbdc::raft::node::is_leader () const -> bool
Indicates whether this node is the current raft leader.
Returns
true if this node is the leader.
Definition at line 157 of file node.cpp.
last_log_idx()
auto cbdc::raft::node::last_log_idx () const -> uint64_t
Returns the last replicated log index.
Returns
log index.
Definition at line 190 of file node.cpp.
operator=() [1/2]
auto cbdc::raft::node::operator= (const node &) -> node &=delete delete
operator=() [2/2]
auto cbdc::raft::node::operator= (node &&) -> node &=delete delete
replicate()
auto cbdc::raft::node::replicate (nuraft::ptr< nuraft::buffer > new_log, const callback_type & result_fn) const -> bool
Replicates the given log entry in the cluster.
Calls the given callback with the state machine execution result.
Parameters
new_log log entry to replicate.
result_fn callback function to call asynchronously with the state machine execution result.
Returns
true if the log entry was accepted for replication.
Definition at line 161 of file node.cpp.
replicate_sync()
auto cbdc::raft::node::replicate_sync (const nuraft::ptr< nuraft::buffer > & new_log) const -> std::optional<nuraft::ptr<nuraft::buffer>>
Replicates the provided log entry and returns the results from the state machine if the replication was successful.
The method will block until the result is available or replication has failed.
Parameters
new_log raft log entry to replicate
Returns
result from state machine or empty optional if replication failed
Definition at line 175 of file node.cpp.
stop()
void cbdc::raft::node::stop ()
Shut down the NuRaft instance.
Definition at line 198 of file node.cpp.
Referenced by cbdc::atomizer::controller::~controller(), and ~node().
The documentation for this class was generated from the following files:
node.hpp
node.cpp