OpenCBDC Transaction Processor: cbdc::blocking_queue< T > Class Template Reference
cbdc::blocking_queue< T > Class Template Reference
Thread-safe producer-consumer FIFO queue supporting multiple concurrent producers and consumers.
#include <blocking_queue.hpp>
Public Member Functions
blocking_queue ()=default
blocking_queue (const blocking_queue &)=delete
auto operator= (const blocking_queue &) -> blocking_queue &=delete
blocking_queue (blocking_queue &&)=delete
auto operator= (blocking_queue &&) -> blocking_queue &=delete
~blocking_queue ()
Destructor.
void push (const T &item)
Pushes an element onto the queue and notifies at most one waiting consumer.
auto pop (T &item) -> bool
Pops an element from the queue.
void clear ()
Clears the queue and unblocks waiting consumers.
Detailed Description
template<typename T>
class cbdc::blocking_queue< T >
Thread-safe producer-consumer FIFO queue supporting multiple concurrent producers and consumers.
Template Parameters
type of object stored in the queue.
Definition at line 19 of file blocking_queue.hpp.
Constructor & Destructor Documentation
blocking_queue() [1/3]
template<typename T > cbdc::blocking_queue< T >::blocking_queue () default
blocking_queue() [2/3]
template<typename T > cbdc::blocking_queue< T >::blocking_queue (const blocking_queue< T > &) delete
blocking_queue() [3/3]
template<typename T > cbdc::blocking_queue< T >::blocking_queue (blocking_queue< T > &&) delete
~blocking_queue()
template<typename T > cbdc::blocking_queue< T >::~blocking_queue () inline
Destructor.
Clears the queue and unblocks any waiting consumers.
Definition at line 32 of file blocking_queue.hpp.
References cbdc::blocking_queue< T >::clear().
Member Function Documentation
clear()
template<typename T > void cbdc::blocking_queue< T >::clear () inline
Clears the queue and unblocks waiting consumers.
Definition at line 77 of file blocking_queue.hpp.
Referenced by cbdc::blocking_queue< T >::~blocking_queue().
operator=() [1/2]
template<typename T > auto cbdc::blocking_queue< T >::operator= (blocking_queue< T > &&) -> blocking_queue &=delete delete
operator=() [2/2]
template<typename T > auto cbdc::blocking_queue< T >::operator= (const blocking_queue< T > &) -> blocking_queue &=delete delete
pop()
template<typename T > auto cbdc::blocking_queue< T >::pop (T & item) -> bool inline
Pops an element from the queue.
Blocks if the queue is empty. Unblocks on destruction or clear without returning an element.
Parameters
item object into which to move the popped element.
Returns
true on success, false if interrupted by clear() or destruction.
Definition at line 55 of file blocking_queue.hpp.
push()
template<typename T > void cbdc::blocking_queue< T >::push (const T & item) inline
Pushes an element onto the queue and notifies at most one waiting consumer.
Parameters
item object to push onto the queue.
Definition at line 39 of file blocking_queue.hpp.
Referenced by cbdc::network::peer::send().
The documentation for this class was generated from the following file:
blocking_queue.hpp