OpenCBDC Transaction Processor: cbdc::transaction Namespace Reference
cbdc::transaction Namespace Reference
Namespaces
namespace validation
Data Structures
struct compact_tx
A condensed, hash-only transaction representation.
struct compact_tx_hasher
struct full_tx
A complete transaction.
struct input
An input for a new transaction.
struct out_point
The unique identifier of a specific output from a transaction.
struct output
An output of a transaction.
class wallet
Cryptographic wallet for digital currency assets and secrets.
Functions
auto tx_id (const full_tx &tx) noexcept -> hash_t
Calculates the unique hash of a full transaction.
auto input_from_output (const full_tx &tx, size_t i, const hash_t &txid) -> std::optional< input >
Converts the output at the specified index to an input.
auto input_from_output (const full_tx &tx, size_t i) -> std::optional< input >
Calls input_from_output after calculating the TXID.
auto uhs_id_from_output (const hash_t &entropy, uint64_t i, const output &output) -> hash_t
Function Documentation
input_from_output() [1/2]
auto cbdc::transaction::input_from_output (const full_tx & tx, size_t i) -> std::optional< input >
Calls input_from_output after calculating the TXID.
Parameters
tx the transaction from which to read outputs
i index of the target output
Returns
result of input_from_output(tx, i, tx_id(tx))
Definition at line 95 of file transaction.cpp.
References input_from_output(), and tx_id().
input_from_output() [2/2]
auto cbdc::transaction::input_from_output (const full_tx & tx, size_t i, const hash_t & txid) -> std::optional< input >
Converts the output at the specified index to an input.
Parameters
tx the transaction from which to read outputs
i index of the target output
txid the txid of the transaction
Returns
resultant input, or std::nullopt if i is invalid.
Definition at line 83 of file transaction.cpp.
References cbdc::transaction::out_point::m_index, cbdc::transaction::input::m_prevout, cbdc::transaction::input::m_prevout_data, and cbdc::transaction::out_point::m_tx_id.
Referenced by cbdc::transaction::wallet::confirm_transaction(), cbdc::transaction::wallet::export_send_inputs(), and input_from_output().
tx_id()
auto cbdc::transaction::tx_id (const full_tx & tx) -> hash_t noexcept
Calculates the unique hash of a full transaction.
Returns a cryptographic hash of the inputs concatenated with the outputs (which are first transformed into inputs). Because output owners cannot reuse outputs across different transactions, this method will always generate a unique identifier for valid transactions.
Parameters
tx the full_tx to hash
Returns
the resultant hash of the transaction
Definition at line 68 of file transaction.cpp.
References cbdc::make_buffer().
Referenced by cbdc::client::abandon_transaction(), cbdc::watchtower::watchtower::add_errors(), cbdc::transaction::validation::check_p2pk_witness_signature(), cbdc::twophase_client::check_tx_id(), cbdc::locking_shard::locking_shard::check_tx_id(), cbdc::locking_shard::rpc::status_client::check_tx_id(), cbdc::watchtower::error_cache::check_tx_id(), cbdc::transaction::compact_tx::compact_tx(), cbdc::transaction::wallet::confirm_transaction(), cbdc::client::confirm_transaction(), confirmtx_command(), cbdc::sentinel::controller::execute_transaction(), cbdc::sentinel_2pc::controller::execute_transaction(), cbdc::watchtower::watchtower::handle_status_update_request(), input_from_output(), mint_command(), print_tx_result(), cbdc::twophase_client::send_mint_tx(), cbdc::client::send_transaction(), cbdc::transaction::wallet::sign(), cbdc::atomizer_client::sync(), and cbdc::twophase_client::sync().
uhs_id_from_output()
auto cbdc::transaction::uhs_id_from_output (const hash_t & entropy, uint64_t i, const output & output) -> hash_t
Definition at line 101 of file transaction.cpp.
References cbdc::make_buffer().
Referenced by cbdc::transaction::compact_tx::compact_tx().