OpenCBDC Transaction Processor: cbdc::transaction::validation Namespace Reference
cbdc::transaction::validation Namespace Reference
Data Structures
struct input_error
An error that may occur when sentinels validate inputs.
struct output_error
An error that may occur when sentinels validate transaction outputs.
struct witness_error
An error that may occur when sentinels validate witness commitments.
Typedefs
using tx_error = std::variant< input_error, output_error, witness_error, tx_error_code >
An error that may occur when sentinels or clients statically validate a transaction.
Enumerations
enum class witness_program_type : uint8_t { p2pk = 0x0 }
Specifies how validators should interpret the witness program.
enum class input_error_code : uint8_t { duplicate , data_error }
Types of input validation errors.
enum class output_error_code : uint8_t { zero_value }
A transaction input validation error.
enum class witness_error_code : uint8_t {
missing_witness_program_type , unknown_witness_program_type , malformed , program_mismatch ,
invalid_public_key , invalid_signature
}
Types of errors that may occur when sentinels validate witness commitments.
enum class tx_error_code : uint8_t {
no_inputs , no_outputs , missing_witness , asymmetric_values ,
value_overflow
}
Types of errors that may occur when a sentinel statically validates a transaction.
Functions
auto check_tx (const transaction::full_tx &tx) -> std::optional< tx_error >
Runs static validation checks on the given transaction.
auto check_tx_structure (const cbdc::transaction::full_tx &tx) -> std::optional< tx_error >
auto check_input_structure (const cbdc::transaction::input &inp) -> std::optional< std::pair< input_error_code, std::optional< output_error_code > > >
auto check_in_out_set (const cbdc::transaction::full_tx &tx) -> std::optional< tx_error >
auto check_witness (const cbdc::transaction::full_tx &tx, size_t idx) -> std::optional< witness_error_code >
auto check_p2pk_witness (const cbdc::transaction::full_tx &tx, size_t idx) -> std::optional< witness_error_code >
auto check_p2pk_witness_len (const cbdc::transaction::full_tx &tx, size_t idx) -> std::optional< witness_error_code >
auto check_p2pk_witness_commitment (const cbdc::transaction::full_tx &tx, size_t idx) -> std::optional< witness_error_code >
auto check_p2pk_witness_signature (const cbdc::transaction::full_tx &tx, size_t idx) -> std::optional< witness_error_code >
auto check_input_count (const cbdc::transaction::full_tx &tx) -> std::optional< tx_error >
auto check_output_count (const cbdc::transaction::full_tx &tx) -> std::optional< tx_error >
auto check_witness_count (const cbdc::transaction::full_tx &tx) -> std::optional< tx_error >
auto check_input_set (const cbdc::transaction::full_tx &tx) -> std::optional< tx_error >
auto check_output_value (const cbdc::transaction::output &out) -> std::optional< output_error_code >
auto get_p2pk_witness_commitment (const pubkey_t &payee) -> hash_t
auto to_string (cbdc::transaction::validation::tx_error_code err) -> std::string
auto to_string (cbdc::transaction::validation::input_error_code err) -> std::string
auto to_string (cbdc::transaction::validation::output_error_code err) -> std::string
auto to_string (const cbdc::transaction::validation::input_error &err) -> std::string
auto to_string (cbdc::transaction::validation::witness_error_code err) -> std::string
auto to_string (const witness_error &err) -> std::string
auto to_string (const output_error &err) -> std::string
auto to_string (const tx_error &err) -> std::string
Typedef Documentation
tx_error
using cbdc::transaction::validation::tx_error = typedef std:: variant<input_error, output_error, witness_error, tx_error_code>
An error that may occur when sentinels or clients statically validate a transaction.
A transaction can fail validation because of an error in the inputs, outputs, witnesses, or because the transaction-local invariants do not hold.
Definition at line 113 of file validation.hpp.
Enumeration Type Documentation
input_error_code
enum class cbdc::transaction::validation::input_error_code : uint8_t strong
Types of input validation errors.
Enumerator
duplicate
More than one transaction input contains the same output.
data_error
A transaction input includes invalid output data.
Definition at line 30 of file validation.hpp.
output_error_code
enum class cbdc::transaction::validation::output_error_code : uint8_t strong
A transaction input validation error.
Enumerator
zero_value
The output's value is 0.
Definition at line 37 of file validation.hpp.
tx_error_code
enum class cbdc::transaction::validation::tx_error_code : uint8_t strong
Types of errors that may occur when a sentinel statically validates a transaction.
Enumerator
no_inputs
There are no inputs.
no_outputs
There are no outputs.
missing_witness
The number of witnesses and inputs do not match.
asymmetric_values
The total values of inputs and outputs do not match.
value_overflow
The total value of inputs/outputs overflows a 64-bit integer.
Definition at line 75 of file validation.hpp.
witness_error_code
enum class cbdc::transaction::validation::witness_error_code : uint8_t strong
Types of errors that may occur when sentinels validate witness commitments.
Enumerator
missing_witness_program_type
The witness did not provide a witness_program_type.
unknown_witness_program_type
The validation system does not recognize the provided witness_program_type.
malformed
The witness's format appears invalid.
program_mismatch
The witness's specified program doesn't match its commitment.
invalid_public_key
The witness's public key is invalid.
invalid_signature
The witness's signature is invalid.
Definition at line 60 of file validation.hpp.
witness_program_type
enum class cbdc::transaction::validation::witness_program_type : uint8_t strong
Specifies how validators should interpret the witness program.
Enumerator
p2pk
Pay to Public Key.
Definition at line 21 of file validation.hpp.
Function Documentation
check_in_out_set()
auto cbdc::transaction::validation::check_in_out_set (const cbdc::transaction::full_tx & tx) -> std::optional< tx_error >
Definition at line 111 of file validation.cpp.
References asymmetric_values, and value_overflow.
Referenced by check_tx().
check_input_count()
auto cbdc::transaction::validation::check_input_count (const cbdc::transaction::full_tx & tx) -> std::optional< tx_error >
Definition at line 243 of file validation.cpp.
References no_inputs.
Referenced by check_tx_structure().
check_input_set()
auto cbdc::transaction::validation::check_input_set (const cbdc::transaction::full_tx & tx) -> std::optional< tx_error >
Definition at line 270 of file validation.cpp.
References duplicate.
Referenced by check_tx_structure().
check_input_structure()
auto cbdc::transaction::validation::check_input_structure (const cbdc::transaction::input & inp) -> std::optional< std::pair< input_error_code, std::optional< output_error_code > > >
Definition at line 100 of file validation.cpp.
References check_output_value(), and data_error.
Referenced by check_tx().
check_output_count()
auto cbdc::transaction::validation::check_output_count (const cbdc::transaction::full_tx & tx) -> std::optional< tx_error >
Definition at line 252 of file validation.cpp.
References no_outputs.
Referenced by check_tx_structure().
check_output_value()
auto cbdc::transaction::validation::check_output_value (const cbdc::transaction::output & out) -> std::optional< output_error_code >
Definition at line 288 of file validation.cpp.
References zero_value.
Referenced by check_input_structure(), and check_tx().
check_p2pk_witness()
auto cbdc::transaction::validation::check_p2pk_witness (const cbdc::transaction::full_tx & tx, size_t idx) -> std::optional< witness_error_code >
Definition at line 158 of file validation.cpp.
References check_p2pk_witness_commitment(), check_p2pk_witness_len(), and check_p2pk_witness_signature().
Referenced by check_witness().
check_p2pk_witness_commitment()
auto cbdc::transaction::validation::check_p2pk_witness_commitment (const cbdc::transaction::full_tx & tx, size_t idx) -> std::optional< witness_error_code >
Definition at line 190 of file validation.cpp.
References cbdc::hash_data(), and program_mismatch.
Referenced by check_p2pk_witness().
check_p2pk_witness_len()
auto cbdc::transaction::validation::check_p2pk_witness_len (const cbdc::transaction::full_tx & tx, size_t idx) -> std::optional< witness_error_code >
Definition at line 179 of file validation.cpp.
References malformed.
Referenced by check_p2pk_witness().
check_p2pk_witness_signature()
auto cbdc::transaction::validation::check_p2pk_witness_signature (const cbdc::transaction::full_tx & tx, size_t idx) -> std::optional< witness_error_code >
Definition at line 207 of file validation.cpp.
References invalid_public_key, invalid_signature, and cbdc::transaction::tx_id().
Referenced by check_p2pk_witness().
check_tx()
auto cbdc::transaction::validation::check_tx (const transaction::full_tx & tx) -> std::optional< tx_error >
Runs static validation checks on the given transaction.
Note
This function returns immediately on the first-found error.
Parameters
tx transaction to validate
Returns
null if transaction is valid, otherwise error information
Definition at line 36 of file validation.cpp.
References check_in_out_set(), check_input_structure(), check_output_value(), check_tx_structure(), and check_witness().
Referenced by cbdc::sentinel::controller::execute_transaction(), and cbdc::sentinel_2pc::controller::execute_transaction().
check_tx_structure()
auto cbdc::transaction::validation::check_tx_structure (const cbdc::transaction::full_tx & tx) -> std::optional< tx_error >
Definition at line 75 of file validation.cpp.
References check_input_count(), check_input_set(), check_output_count(), and check_witness_count().
Referenced by check_tx().
check_witness()
auto cbdc::transaction::validation::check_witness (const cbdc::transaction::full_tx & tx, size_t idx) -> std::optional< witness_error_code >
Definition at line 138 of file validation.cpp.
References check_p2pk_witness(), missing_witness_program_type, p2pk, and unknown_witness_program_type.
Referenced by check_tx().
check_witness_count()
auto cbdc::transaction::validation::check_witness_count (const cbdc::transaction::full_tx & tx) -> std::optional< tx_error >
Definition at line 261 of file validation.cpp.
References missing_witness.
Referenced by check_tx_structure().
get_p2pk_witness_commitment()
auto cbdc::transaction::validation::get_p2pk_witness_commitment (const pubkey_t & payee) -> hash_t
Definition at line 297 of file validation.cpp.
References cbdc::hash_data(), p2pk, and cbdc::to_vector().
Referenced by cbdc::transaction::wallet::export_send_inputs(), cbdc::transaction::wallet::generate_key(), cbdc::transaction::wallet::load(), cbdc::transaction::wallet::mint_new_coins(), cbdc::transaction::wallet::seed(), and cbdc::transaction::wallet::send_to().
to_string() [1/8]
auto cbdc::transaction::validation::to_string (cbdc::transaction::validation::input_error_code err) -> std::string
Definition at line 328 of file validation.cpp.
References data_error, and duplicate.
to_string() [2/8]
auto cbdc::transaction::validation::to_string (cbdc::transaction::validation::output_error_code err) -> std::string
Definition at line 340 of file validation.cpp.
References zero_value.
to_string() [3/8]
auto cbdc::transaction::validation::to_string (cbdc::transaction::validation::tx_error_code err) -> std::string
Definition at line 308 of file validation.cpp.
References asymmetric_values, missing_witness, no_inputs, no_outputs, and value_overflow.
Referenced by cbdc::sentinel_2pc::controller::execute_transaction(), print_tx_result(), and to_string().
to_string() [4/8]
auto cbdc::transaction::validation::to_string (cbdc::transaction::validation::witness_error_code err) -> std::string
Definition at line 360 of file validation.cpp.
References invalid_public_key, invalid_signature, malformed, missing_witness_program_type, program_mismatch, and unknown_witness_program_type.
to_string() [5/8]
auto cbdc::transaction::validation::to_string (const cbdc::transaction::validation::input_error & err) -> std::string
Definition at line 350 of file validation.cpp.
References to_string().
to_string() [6/8]
auto cbdc::transaction::validation::to_string (const output_error & err) -> std::string
Definition at line 390 of file validation.cpp.
References to_string().
to_string() [7/8]
auto cbdc::transaction::validation::to_string (const tx_error & err) -> std::string
Definition at line 395 of file validation.cpp.
References to_string().
Referenced by to_string().
to_string() [8/8]
auto cbdc::transaction::validation::to_string (const witness_error & err) -> std::string
Definition at line 385 of file validation.cpp.
References to_string().