OpenCBDC Transaction Processor: cbdc::sentinel Namespace Reference
cbdc::sentinel Namespace Reference
Namespaces
namespace rpc
Data Structures
class async_interface
Interface for an asynchronous sentinel.
class controller
Sentinel implementation.
class interface
Interface for a sentinel.
struct response
Sentinel response message.
struct shard_info
Sentinel-specific representation of shard network information.
Typedefs
using request = transaction::full_tx
Sentinel request message.
Enumerations
enum class tx_status { pending , static_invalid , state_invalid , confirmed }
Status of the transaction following sentinel processing.
Functions
auto to_string (tx_status status) -> std::string
Return a human-readable string describing a tx_status.
Typedef Documentation
request
using cbdc::sentinel::request = typedef transaction::full_tx
Sentinel request message.
Definition at line 49 of file sentinel/interface.hpp.
Enumeration Type Documentation
tx_status
enum class cbdc::sentinel::tx_status strong
Status of the transaction following sentinel processing.
Enumerator
pending
Statically valid, and the sentinel has submitted the transaction to the network for processing.
static_invalid
Statically invalid. Must be fixed and resubmitted.
state_invalid
Statically valid, but rejected by the shards for trying to spend inputs either that do not exist or that a previous transaction already spent.
confirmed
Executed to completion.
Included in a block generated by the atomizer cluster or completed by a distributed transaction batch coordinated between locking shards.
Definition at line 18 of file sentinel/interface.hpp.
Function Documentation
to_string()
auto cbdc::sentinel::to_string (tx_status status) -> std::string
Return a human-readable string describing a tx_status.
Parameters
status tx_status to print.
Returns
human-readable string.
Definition at line 15 of file sentinel/interface.cpp.
References confirmed, pending, state_invalid, and static_invalid.
Referenced by cbdc::archiver::controller::digest_block(), cbdc::archiver::controller::get_block(), cbdc::archiver::controller::init_best_block(), print_tx_result(), cbdc::config::read_archiver_options(), cbdc::config::read_atomizer_options(), cbdc::config::read_coordinator_options(), cbdc::config::read_sentinel_options(), cbdc::config::read_shard_endpoints(), cbdc::config::read_shard_options(), cbdc::config::read_watchtower_options(), and cbdc::client::send_transaction().